*******************************************************************************
* Script generated on ${headers.Date} at ${headers.Time}
* Script generated by user ${headers.User} on host ${headers.Host}
* Author: ${headers.Author}
* Queue manager name: ${headers.QueueManager}
* Integration: ${headers.Integration}
*******************************************************************************